name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # 1. Base Configuration (Wide layout)
          user: DeathGun44
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          theme: dracula
          config_display: large
          
          # 2. "Notable" 
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          
          # 3. Achievements - Adds colorful "Trophies"
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # 4. Languages - The colored bar graph you liked
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          
          # 5. Lines of Code 
          plugin_lines: yes
          
          # 6. Calendar 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
